vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /img/profile
            upload_destination: '%kernel.project_dir%/public/img/profile'
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
